/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/rook/rook/pkg/apis/noobaa.rook.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSystems implements SystemInterface
type FakeSystems struct {
	Fake *FakeNoobaaV1alpha1
	ns   string
}

var systemsResource = schema.GroupVersionResource{Group: "noobaa.rook.io", Version: "v1alpha1", Resource: "systems"}

var systemsKind = schema.GroupVersionKind{Group: "noobaa.rook.io", Version: "v1alpha1", Kind: "System"}

// Get takes name of the system, and returns the corresponding system object, and an error if there is any.
func (c *FakeSystems) Get(name string, options v1.GetOptions) (result *v1alpha1.System, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(systemsResource, c.ns, name), &v1alpha1.System{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.System), err
}

// List takes label and field selectors, and returns the list of Systems that match those selectors.
func (c *FakeSystems) List(opts v1.ListOptions) (result *v1alpha1.SystemList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(systemsResource, systemsKind, c.ns, opts), &v1alpha1.SystemList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SystemList{ListMeta: obj.(*v1alpha1.SystemList).ListMeta}
	for _, item := range obj.(*v1alpha1.SystemList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested systems.
func (c *FakeSystems) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(systemsResource, c.ns, opts))

}

// Create takes the representation of a system and creates it.  Returns the server's representation of the system, and an error, if there is any.
func (c *FakeSystems) Create(system *v1alpha1.System) (result *v1alpha1.System, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(systemsResource, c.ns, system), &v1alpha1.System{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.System), err
}

// Update takes the representation of a system and updates it. Returns the server's representation of the system, and an error, if there is any.
func (c *FakeSystems) Update(system *v1alpha1.System) (result *v1alpha1.System, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(systemsResource, c.ns, system), &v1alpha1.System{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.System), err
}

// Delete takes name of the system and deletes it. Returns an error if one occurs.
func (c *FakeSystems) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(systemsResource, c.ns, name), &v1alpha1.System{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSystems) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(systemsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SystemList{})
	return err
}

// Patch applies the patch and returns the patched system.
func (c *FakeSystems) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.System, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(systemsResource, c.ns, name, pt, data, subresources...), &v1alpha1.System{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.System), err
}
