/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/rook/rook/pkg/apis/noobaa.rook.io/v1alpha1"
	scheme "github.com/rook/rook/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SystemsGetter has a method to return a SystemInterface.
// A group's client should implement this interface.
type SystemsGetter interface {
	Systems(namespace string) SystemInterface
}

// SystemInterface has methods to work with System resources.
type SystemInterface interface {
	Create(*v1alpha1.System) (*v1alpha1.System, error)
	Update(*v1alpha1.System) (*v1alpha1.System, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.System, error)
	List(opts v1.ListOptions) (*v1alpha1.SystemList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.System, err error)
	SystemExpansion
}

// systems implements SystemInterface
type systems struct {
	client rest.Interface
	ns     string
}

// newSystems returns a Systems
func newSystems(c *NoobaaV1alpha1Client, namespace string) *systems {
	return &systems{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the system, and returns the corresponding system object, and an error if there is any.
func (c *systems) Get(name string, options v1.GetOptions) (result *v1alpha1.System, err error) {
	result = &v1alpha1.System{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("systems").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Systems that match those selectors.
func (c *systems) List(opts v1.ListOptions) (result *v1alpha1.SystemList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SystemList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("systems").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested systems.
func (c *systems) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("systems").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a system and creates it.  Returns the server's representation of the system, and an error, if there is any.
func (c *systems) Create(system *v1alpha1.System) (result *v1alpha1.System, err error) {
	result = &v1alpha1.System{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("systems").
		Body(system).
		Do().
		Into(result)
	return
}

// Update takes the representation of a system and updates it. Returns the server's representation of the system, and an error, if there is any.
func (c *systems) Update(system *v1alpha1.System) (result *v1alpha1.System, err error) {
	result = &v1alpha1.System{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("systems").
		Name(system.Name).
		Body(system).
		Do().
		Into(result)
	return
}

// Delete takes name of the system and deletes it. Returns an error if one occurs.
func (c *systems) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("systems").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *systems) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("systems").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched system.
func (c *systems) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.System, err error) {
	result = &v1alpha1.System{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("systems").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
