###############################################################################
#
# CRD: NooBaaBackingStore
#
# WAIT !!! No need to create this manually, the operator does it.
#
###############################################################################
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: noobaabackingstores.noobaa.rook.io
spec:
  scope: Namespaced
  group: noobaa.rook.io
  names:
    kind: NooBaaBackingStore
    plural: noobaabackingstores
    singular: noobaabackingstore
    listKind: NooBaaBackingStoreList
    shortNames: ["nbstore"]
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  # Support extra REST API subresources for this resource
  subresources:
    status: {} # enabled
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
